apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-pguser-scorpiobroker
  namespace: scorpiobroker
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: postgres-pguser-scorpiobroker
  dataFrom:
    - extract:
        key: scorpiobroker/kv/postgres-pguser-scorpiobroker
