apiVersion: v1
kind: Service
metadata:
  name: postgresql-nodeport
  namespace: postgres
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5432-5432
    nodePort: 30432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgres-operator.crunchydata.com/role: master
  sessionAffinity: None
  type: NodePort
