apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-unseal-tasks
  namespace: vault
data:
  main.yaml: |
    ---
    - name: Set vault pod name
      set_fact:
        VAULT_POD: "vault-0"

    - name: Get vault init dev secrets
      set_fact:
        VAULT_UNSEAL_KEY: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='vault-init', namespace=VAULT_NAMESPACE, validate_certs=false)[0].data.VAULT_UNSEAL_KEY | b64decode }}"
        VAULT_ROOT_TOKEN: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='vault-init', namespace=VAULT_NAMESPACE, validate_certs=false)[0].data.VAULT_ROOT_TOKEN | b64decode }}"
      when: VAULT_UNSEAL_KEY is not defined and VAULT_ROOT_TOKEN is not defined or VAULT_UNSEAL_KEY == '' and VAULT_ROOT_TOKEN == ''

    - block:
        - name: Unseal vault
          kubernetes.core.k8s_exec:
            namespace: "{{ VAULT_NAMESPACE }}"
            pod: "{{ VAULT_POD }}"
            command: >-
              vault operator unseal -address http://vault.vault.svc.cluster.local:8200 -ca-path /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt "{{ VAULT_UNSEAL_KEY }}"
          register: vault_unseal
          ignore_errors: true
        - debug:
            var: vault_unseal
