apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-initial-admin
  namespace: keycloak
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: keycloak-initial-admin
  dataFrom:
    - extract:
        key: keycloak/kv/keycloak-initial-admin
