apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances:
    - replicas: 1
      name: 'postgres'
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
            cpu: '200m'
            memory: '200Mi'
          limits:
            cpu: '1'
            memory: '1Gi'
      walVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
            cpu: '200m'
            memory: '200Mi'
          limits:
            cpu: '200m'
            memory: '200Mi'
      resources:
        requests:
          cpu: '200m'
          memory: '200Mi'
        limits:
          cpu: '1'
          memory: '1Gi'
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-15.1-3.3-0
  postgresVersion: 15
  openshift: true
  postGISVersion: 3.3.0
  users:
    - name: keycloak
      options: "SUPERUSER"
      databases:
        - keycloak
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host all all all md5"
          - "local all all trust"
