apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-database-setup-tasks
  namespace: keycloak
data:
  main.yaml: |
    ---
    - name: Get postgres pod by label
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: postgres
        label_selectors:
          - postgres-operator.crunchydata.com/role=master
      register: postgres_pod_info
    - name: Set postgres pod name
      set_fact:
        POSTGRES_POD_NAME: "{{ postgres_pod_info.resources[0].metadata.name }}"
        POSTGRES_KEYCLOAK_PASSWORD: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='postgres-pguser-keycloak', namespace='keycloak')[0].data['password'] | b64decode }}"
    - name: "Create database user keycloak"
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: "{{ POSTGRES_POD_NAME }}"
        command: >-
          env psql -U postgres postgres -c 
          "create user keycloak password '{{ POSTGRES_KEYCLOAK_PASSWORD }}';"
      register: create_database_user
    - name: "Create database keycloak"
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: "{{ POSTGRES_POD_NAME }}"
        command: >-
          env psql -U postgres postgres -c 
          "create database keycloak owner keycloak;"
