apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2026-03-17T03:56:49Z"
  generation: 1
  labels:
    operators.coreos.com/etcd.sensu: ""
  name: etcd
  namespace: sensu
  resourceVersion: "1190058"
  uid: 1792b00a-76f6-42ab-a98c-72b87dfed03e
spec:
  channel: singlenamespace-alpha
  installPlanApproval: Automatic
  name: etcd
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: etcdoperator.v0.9.4
