apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: alpha-8
  namespace: vault-admin
spec:
  # Add fields here
  authentication: 
    path: kubernetes
    role: policy-admin
  connection:
    address: 'http://vault.vault.svc.cluster.local:8200'
  passwordPolicy: |
    length = 8
    rule "charset" {
      charset = "abcdefghjkmnpqrstuvwxyz"
      min-chars = 1
    }
