apiVersion: v1
kind: ConfigMap
metadata:
  name: solr-setup-tasks
  namespace: solr
data:
  main.yaml: |
    ---
    - name: "Download computate configset: curl -k https://raw.githubusercontent.com/computate-org/computate/refs/heads/main/config/solr/computate-configset.zip -o /tmp/computate-configset.zip"
      kubernetes.core.k8s_exec:
        namespace: solr
        pod: solr-solrcloud-0
        command: >-
          curl -k https://raw.githubusercontent.com/computate-org/computate/refs/heads/main/config/solr/computate-configset.zip -o /tmp/computate-configset.zip
    - name: >-
        Upload default computate configset: 
        curl -k -X POST -u "admin:{{ query('kubernetes.core.k8s', kind='Secret', resource_name='solr-solrcloud-security-bootstrap', namespace='solr')[0].data['admin'] | b64decode }}" 
          -H "Content-Type:application/octet-stream" 
          --data-binary @/tmp/computate-configset.zip 
          "https://solr-solr.apps-crc.testing/solr/admin/configs?action=UPLOAD&name=computate&overwrite=true"
      kubernetes.core.k8s_exec:
        namespace: solr
        pod: solr-solrcloud-0
        command: >-
          bash -c '
          curl -k -X POST -u "admin:{{ query('kubernetes.core.k8s', kind='Secret', resource_name='solr-solrcloud-security-bootstrap', namespace='solr')[0].data['admin'] | b64decode }}" 
          -H "Content-Type:application/octet-stream" 
          --data-binary @/tmp/computate-configset.zip 
          "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=computate&overwrite=true"
          '
      register: upload_computate_configset
    - name: Debug upload_computate_configset
      debug:
        var: upload_computate_configset
    - name: >-
        Create computate collection: 
        SOLR_AUTH_TYPE=basic 
        SOLR_AUTHENTICATION_OPTS="-Dbasicauth=admin:{{ query('kubernetes.core.k8s', kind='Secret', resource_name='solr-solrcloud-security-bootstrap', namespace='solr')[0].data['admin'] | b64decode }}" 
        /opt/solr/bin/solr create_collection --solr-url http://localhost:8983 -c computate -n computate'
      kubernetes.core.k8s_exec:
        namespace: solr
        pod: solr-solrcloud-0
        command: >-
          bash -c '
          SOLR_AUTH_TYPE=basic
          SOLR_AUTHENTICATION_OPTS="-Dbasicauth=admin:{{ query('kubernetes.core.k8s', kind='Secret', resource_name='solr-solrcloud-security-bootstrap', namespace='solr')[0].data['admin'] | b64decode }}" 
          /opt/solr/bin/solr create_collection --solr-url http://localhost:8983 -c computate -n computate
          '
      register: create_computate_collection
      ignore_errors: true
    - name: Debug create_computate_collection
      debug:
        var: create_computate_collection
    - name: Test create computate collection success
      fail:
        msg: "{{ command_status }}"
      when: create_computate_collection.failed and create_computate_collection is not search("already exists")
