apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo
  namespace: forgejo
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  dataFrom:
    - extract:
        key: forgejo/kv/postgres-pguser-forgejo-password
  target:
    name: postgres-pguser-forgejo
    template:
      type: Opaque
      engineVersion: v2
      data:
        DB_TYPE: postgres
        HOST: postgres.postgres.svc:5432
        NAME: forgejo
        USER: forgejo
        PASSWD: "{{ .password }}"
        SCHEMA: public
