apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  dataFrom:
    - extract:
        key: forgejo/kv/forgejo-admin
  target:
    name: forgejo-admin
    template:
      type: Opaque
      engineVersion: v2
      data:
        username: forgejo
        password: "{{ .password }}"
