apiVersion: v1
kind: Service
metadata:
  name: zookeeper-nodeport
  namespace: zookeeper
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 2181-2181
    nodePort: 30081
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app.kubernetes.io/name: zookeeper
  sessionAffinity: None
  type: NodePort
