apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-pguser-keycloak
  namespace: keycloak
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: postgres-pguser-keycloak
  dataFrom:
    - extract:
        key: keycloak/kv/postgres-pguser-keycloak
