apiVersion: v1
kind: ConfigMap
metadata:
  name: database-setup-tasks
  namespace: scorpiobroker
data:
  main.yaml: |
    ---
    - name: Get postgres pod by label
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: postgres
        label_selectors:
          - postgres-operator.crunchydata.com/role=master
      register: postgres_pod_info
    - name: Set postgres pod name
      set_fact:
        POSTGRES_POD_NAME: "{{ postgres_pod_info.resources[0].metadata.name }}"
        POSTGRES_SCORPIOBROKER_PASSWORD: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='postgres-pguser-scorpiobroker', namespace='scorpiobroker')[0].data['password'] | b64decode }}"
    - name: "Create database user scorpiobroker"
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: "{{ POSTGRES_POD_NAME }}"
        command: >-
          env psql -U postgres postgres -c 
          "create user scorpiobroker password '{{ POSTGRES_SCORPIOBROKER_PASSWORD }}';"
      ignore_errors: true
      register: create_database_user
    - name: Test create database user
      fail:
        msg: "{{ command_status }}"
      when: create_database_user.failed and create_database_user is not search("already exists")
    - name: "Create database scorpiobroker"
      kubernetes.core.k8s_exec:
        namespace: postgres
        pod: "{{ POSTGRES_POD_NAME }}"
        command: >-
          env psql -U postgres postgres -c 
          "create database scorpiobroker owner scorpiobroker;"
      ignore_errors: true
      register: create_database
    - name: Test create database
      fail:
        msg: "{{ command_status }}"
      when: create_database.failed and create_database is not search("already exists")
