---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: solr
  name: solr-setup-exec
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: solr
  name: solr-setup-exec
subjects:
- kind: ServiceAccount
  name: solr-setup
  namespace: solr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: solr-setup-exec
