apiVersion: v1
kind: ServiceAccount
metadata:
  name: valkey
  labels:
    helm.sh/chart: valkey-0.10.0
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey
    app.kubernetes.io/version: "9.1.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
