# Source: valkey/templates/deploy_valkey.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  labels:
    helm.sh/chart: valkey-0.10.0
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey
    app.kubernetes.io/version: "9.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: valkey
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey
        app.kubernetes.io/instance: valkey
      annotations:
        checksum/initconfig: 0f0528edcacd19b622706bce367af446
    spec:
      
      automountServiceAccountToken: false
      serviceAccountName: valkey
      securityContext: {}
      initContainers:
        - name: valkey-init
          image: docker.io/valkey/valkey:9.1.0
          imagePullPolicy: IfNotPresent
          securityContext: {}
          command: [ "/scripts/init.sh" ]
          volumeMounts:
            - name: valkey-data
              mountPath: /data
            - name: scripts
              mountPath: /scripts
      containers:
        - name: valkey
          image: docker.io/valkey/valkey:9.1.0
          imagePullPolicy: IfNotPresent
          command: [ "valkey-server" ]
          args: [ "/data/conf/valkey.conf" ]
          securityContext: {}
          env:
            - name: VALKEY_LOGLEVEL
              value: "notice"
          ports:
            - name: tcp
              containerPort: 6379
              protocol: TCP
          startupProbe:
            exec:
              command: [ "sh", "-c", "valkey-cli ping" ]
          livenessProbe:
            exec:
              command: [ "sh", "-c", "valkey-cli ping" ]
          resources:
            {}
          volumeMounts:
            - name: valkey-data
              mountPath: /data
      volumes:
        - name: scripts
          configMap:
            name: valkey-init-scripts
            defaultMode: 0555
        - name: valkey-data
          emptyDir: {}
