apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-certificate
spec:
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  secretName: keycloak-certificate
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  commonName: keycloak.apps-crc.testing
  subject:
    organizations:
      - MyOrganization
    organizationalUnits:
      - MyUnit
    countries:
      - US
    provinces:
      - CA
    localities:
      - SanFrancisco
  dnsNames:
    - keycloak.apps-crc.testing
